### ISSUE TITLE
errors during making the firmware for ANTSDR E310

### ISSUE THREAD

**Issue by mrbilandi** [MicroPhase/antsdr-fw-patch#10]
I work on ubuntu 22.04, I want to build the firmware but got some errors

1. I got below error first :
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384

and solve it by do the following instruction : 
# initially:
cd path/to/buildroot
git remote add upstream https://github.com/buildroot/buildroot.git
git fetch upstream master

# then (from within the "buildroot" repo or subrepo)
rm -r package/m4
git checkout upstream/master -- package/m4
git add -A
git status
git commit -m "Update m4 library"

----------------------------------------------------------------------------------------
2. and after that I encounter to below error : 
libfakeroot.c:99:40: error: ‘_STAT_VER’ undeclared (first use in this function)    99 | #define INT_NEXT_STAT(a,b) NEXT_STAT64(_STAT_VER,a,b)

and solve it using a patch file (named no_STAT_VER.patch) from 
https://bugs.archlinux.org/task/69572
I placed the patch file into plutosdr-fw/buildroot/package/fakeroot/ 
and this error solved too.

--------------------------------------------------------
3. now after I tried to make I got this below error, and I don't have any Idea how to solve it 

mknod: /media/mojtaba/m2/Projects/ANTSDR/e310_fw/antsdr-fw/buildroot/output/build/buildroot-fs/cpio/target/dev/console: Operation not permitted
make[2]: *** [fs/cpio/cpio.mk:72: /media/mojtaba/m2/Projects/ANTSDR/e310_fw/antsdr-fw/buildroot/output/images/rootfs.cpio] Error 1
make[1]: *** [Makefile:84: _all] Error 2
make[1]: Leaving directory '/media/mojtaba/m2/Projects/ANTSDR/e310_fw/antsdr-fw/buildroot'
make: *** [Makefile:128: buildroot/output/images/rootfs.cpio.gz] Error 2
